#!/bin/sh

USER="www-data"
if [ ! -z "$USER_ID" -a ! -z "$GROUP_ID" ] ; then
	echo "Switching to user"
	USER="user"
	deluser "$USER"
	delgroup "$USER"
	addgroup --gid "$GROUP_ID" "$USER"
	adduser --disabled-password --disabled-login --no-create-home --system --uid "$USER_ID" --gid "$GROUP_ID" "$USER"
fi
export USER

export CATCH_WORKERS_OUTPUT="${CATCH_WORKERS_OUTPUT:-yes}"
echo CATCH_WORKERS_OUTPUT=${CATCH_WORKERS_OUTPUT}

export MAX_CHILDREN="${MAX_CHILDREN:-100}"
echo MAX_CHILDREN=${MAX_CHILDREN}

export START_SERVERS="${START_SERVERS:-20}"
echo START_SERVERS=${START_SERVERS}

export MIN_SPARE_SERVERS="${MIN_SPARE_SERVERS:-10}"
echo MIN_SPARE_SERVERS=${MIN_SPARE_SERVERS}

export MAX_SPARE_SERVERS="${MAX_SPARE_SERVERS:-20}"
echo MAX_SPARE_SERVERS=${MAX_SPARE_SERVERS}

export MEMORY_LIMIT="${MEMORY_LIMIT:-128M}"
echo MEMORY_LIMIT=${MEMORY_LIMIT}

export POST_MAX_FILESIZE="${POST_MAX_FILESIZE:-128M}"
echo POST_MAX_FILESIZE=${POST_MAX_FILESIZE}

export UPLOAD_MAX_FILESIZE="${UPLOAD_MAX_FILESIZE:-32M}"
echo UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE}


SOURCE_POOL_CONFIG=/opt/config/php-fpm.d/pool.conf 
TARGET_POOL_CONFIG=/usr/local/etc/php-fpm.d/pool.conf

echo "creating '$TARGET_POOL_CONFIG' from '$SOURCE_POOL_CONFIG'"
envsubst < "$SOURCE_POOL_CONFIG" > "$TARGET_POOL_CONFIG"
echo "created '$TARGET_POOL_CONFIG'"
