#!/bin/sh

USER="www-data"
if [ ! -z "$USER_ID" -a ! -z "$GROUP_ID" ] ; then
	echo "Switching to user"
	USER="user"
	deluser "$USER"
	delgroup "$USER"
	addgroup --gid "$GROUP_ID" "$USER"
	adduser --disabled-password --disabled-login --no-create-home --system --uid "$USER_ID" --gid "$GROUP_ID" "$USER"
fi

PHP_MAX_CHILDREN="${PHP_MAX_CHILDREN:-100}"
PHP_START_SERVERS="${PHP_START_SERVERS:-20}"
PHP_MIN_SPARE_SERVERS="${PHP_MIN_SPARE_SERVERS:-10}"
PHP_MAX_SPARE_SERVERS="${PHP_MAX_SPARE_SERVERS:-20}"
PHP_MEMORY_LIMIT="${PHP_MEMORY_LIMIT:-128M}"
PHP_POST_MAX_FILESIZE="${PHP_POST_MAX_FILESIZE:-128M}"
PHP_UPLOAD_MAX_FILESIZE="${PHP_UPLOAD_MAX_FILESIZE:-32M}"


SOURCE_POOL_CONFIG=/opt/config/php-fpm.d/pool.conf 
TARGET_POOL_CONFIG=/usr/local/etc/php-fpm.d/pool.conf

echo "creating '$TARGET_POOL_CONFIG' from '$SOURCE_POOL_CONFIG'"
envsubst < "$SOURCE_POOL_CONFIG" > "$TARGET_POOL_CONFIG"
echo "created '$TARGET_POOL_CONFIG'"
